//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется oeav.rc
//
#define IDD_REGIST_LIST                 9
#define OEAV_MEN_RJ                     9
#define IDD_OEAV_DIALOG                 102
#define IDD_BALANCE_REP                 103
#define OEAV_MEN_BO                     103
#define IDD_CARDFILES                   104
#define OEAV_MEN_K                      104
#define IDD_DOCUMENTS                   105
#define OEAV_MEN_D                      105
#define IDD_LOOK_RL                     106
#define OEAV_JSR                        106
#define IDD_LOOK_AB                     107
#define OEAV_KSR                        107
#define IDD_DEF_REP_FORM                108
#define OEAV_CSI                        108
#define IDD_ANALYTICAL_CODES            109
#define OEAV_ASX                        109
#define IDD_ANALYTICAL_TYPES            110
#define OEAV_VSX                        110
#define IDD_ACCOUNT_PLAN                111
#define IDD_ANALYTICAL_TYPES1           111
#define OEAV_SSX                        111
#define OEAV_DSX                        112
#define OEAV_OSX                        113
#define OEAV_PSX                        114
#define OEAV_KRV                        115
#define OEAV_KRV1                       116
#define OEAV_KRJ                        116
#define IDR_MAINFRAME                   128
#define IDI_CREATE                      129
#define IDI_PRINT                       131
#define IDI_FOLDER                      132
#define IDI_FREPORT                     133
#define IDI_BCREPORT                    134
#define IDI_INVENTORY                   135
#define IDI_ANALITIC                    136
#define IDI_OPERATION                   137
#define IDI_DOCUMENT2                   138
#define IDI_PLAN                        139
#define IDI_CODES                       140
#define IDI_ICON1                       141
#define IDI_INPUT                       141
#define IDI_NEXT                        142
#define IDI_PREVIOUS                    143
#define IDI_CANCEL                      144
#define IDI_DELETE                      145
#define IDI_CANCEL2                     146
#define IDI_ADD                         147
#define IDI_ACCEPT                      149
#define IDI_EDIT                        152
#define IDC_STATIC_MAIN_MENU            1000
#define IDC_OPD_PO_1                    1000
#define IDC_STATIC_ID                   1001
#define IDC_OPD_PO_2                    1001
#define IDC_STATIC_NAME                 1002
#define IDC_RS_TITLE                    1002
#define IDC_OPD_PO_3                    1002
#define IDC_TAB_CONTROLLER              1005
#define IDC_BUTTON_SETTINGS             1006
#define IDC_BUTTON_EXIT                 1007
#define IDR_SETTINGS                    1008
#define IDR_EXIT                        1009
#define IDC_RS_EMPLID                   1010
#define IDC_RL_B_LOOKRL                 1011
#define IDC_RL_B_LOOKAB                 1012
#define IDC_RL_B_LOOKRL_Q               1013
#define IDC_BUTTON4                     1014
#define IDC_RL_B_LOOKAB_Q               1014
#define IDC_RL_B_GENERATEAB             1015
#define IDC_RL_B_PRINT_AB               1016
#define IDR_LOOK_BOOK                   1018
#define IDR_LOOK_BOOK2                  1019
#define IDC_LOOKG                       1020
#define IDC_GROUP_Q                     1021
#define IDC_BR_TITLE                    1022
#define IDC_BR_EMPLID                   1023
#define IDC_DC_TITLE                    1026
#define IDC_DC_EMPLID                   1027
#define IDC_CF_TITLE                    1028
#define IDC_CF_EMPLID                   1029
#define IDC_BR_B_REP_DEF                1030
#define IDC_BR_B_OSV_PERIOD             1031
#define IDC_BR_B_LIST_O_PERIOD          1032
#define IDC_CF_B_OPD                    1032
#define IDC_BR_B_BAL_REP_PERIOD         1033
#define IDC_CF_B_PS                     1033
#define IDC_DC_B_MINV                   1033
#define IDC_CF_B_THO                    1034
#define IDC_LRJ_EMPLID                  1034
#define IDC_CF_B_VA                     1035
#define IDC_LRJ_WNDID                   1035
#define IDC_CF_B_KAY                    1036
#define IDC_LRJ_WNDNAME                 1036
#define IDC_LRJ_DATE                    1037
#define IDC_LRJ_DOCUMENT                1038
#define IDC_LRJ_OPERATION               1039
#define IDC_LRJ_E_DATE_FROM             1040
#define IDC_LRJ_E_DOC_NAME              1041
#define IDC_LRJ_E_DOC_ID                1042
#define IDC_LRJ_E_OPERATION             1043
#define IDC_LRJ_DATE_FROM               1044
#define IDC_LRJ_E_DATE                  1045
#define IDC_LRJ_DEBET                   1046
#define IDC_LRJ_E_DEBET_CASH            1047
#define IDC_LRJ_E_DEBET_SOURCE          1048
#define IDC_LRJ_CREDIT                  1049
#define IDC_LRJ_E_CREDIT_CASH           1050
#define IDC_LRJ_E_CREDIT_SOURCE         1051
#define IDC_LRJ_SUM                     1052
#define IDC_LRJ_E_SUM                   1053
#define IDC_LRJ_E_CREDIT_SOURCE2        1054
#define IDC_LRJ_DELETE                  1055
#define IDC_LRJ_NEXT                    1056
#define IDC_LRJ_EXIT                    1057
#define IDC_LRJ_PREV                    1058
#define IDC_LRJ_CHOOSE                  1059
#define IDC_LAB_EMPLID                  1060
#define IDC_LAB_WNDID                   1061
#define IDC_LAB_DATE                    1062
#define IDC_LAB_WNDNAME                 1063
#define IDC_LAB_DOCUMENT                1064
#define IDC_LAB_OPERATION               1065
#define IDC_LAB_E_DATE                  1066
#define IDC_LAB_E_DOC_NAME              1067
#define IDC_LAB_E_DOC_ID                1068
#define IDC_LAB_E_OPERATION             1069
#define IDC_LAB_DATE_FROM               1070
#define IDC_LAB_E_DATE_FROM             1071
#define IDC_LAB_DEBET                   1072
#define IDC_LAB_E_DEBET_CASH            1073
#define IDC_LAB_CREDIT                  1074
#define IDC_LAB_E_CREDIT_CASH           1075
#define IDC_LAB_E_ACC_ID                1076
#define IDC_ACCOUNT                     1077
#define IDC_LAB_E_ACC_NAME              1078
#define IDC_LAB_SEP_1                   1079
#define IDC_LAB_E_CORR_ID               1080
#define IDC_LRJ_SEP_2                   1080
#define IDC_LAB_E_CORR_NAME             1081
#define IDC_LRJ_SEP_3                   1081
#define IDC_LAB_SEP_2                   1082
#define IDC_LAB_SEP_3                   1085
#define IDC_CORR                        1086
#define IDC_LAB_DELETE                  1087
#define IDC_LAB_PREV                    1088
#define IDC_LAB_NEXT                    1089
#define IDC_LAB_EXIT                    1090
#define IDC_LRJ_SEP_1                   1091
#define IDC_LAB_CHOOSE                  1091
#define IDC_DRF_B_EXIT                  1092
#define IDC_DRF_EMPLNAME                1093
#define IDC_DRF_WNDID                   1094
#define IDC_DRF_WNDNAME                 1095
#define IDC_DRF_D_INTERVAL_FROM         1096
#define IDC_DRF_INT_FROM                1097
#define IDC_DRF_D_INTERVAL_TO           1098
#define IDC_DRF_INT_TO                  1099
#define IDC_DRF_ACCOUNT                 1100
#define IDC_DRF_C_ACC                   1104
#define IDC_ACO_EMPLNAME                1107
#define IDC_ACO_WNDID                   1108
#define IDC_ACO_WNDNAME                 1109
#define IDC_ACO_ANALYT_TYPE             1110
#define IDC_ACO_E_ANALYT_CODE           1111
#define IDC_ACO_E_ANALYT_CODE2          1112
#define IDC_ACO_E_ANALYT_TYPE           1112
#define IDC_ATY_E_ANALYT_CODE           1112
#define IDC_ACO_C_ANALYT_TYPES          1113
#define IDC_ACO_B_EXIT                  1114
#define IDC_ACO_B_ADD                   1115
#define IDC_ACO_B_PREV                  1116
#define IDC_ACO_B_NEXT                  1117
#define IDC_ACO_B_DELETE                1118
#define IDC_ACO_ANALYT_CODE             1119
#define IDC_ATY_WNDNAME                 1120
#define IDC_ACO_B_EDIT                  1120
#define IDC_ATY_EMPLNAME                1121
#define IDC_ATY_WNDID                   1122
#define IDC_ATY_ANALYT_TYPE             1123
#define IDC_ACO_B_CHOOSE2               1123
#define IDC_ATY_ANALYT_CODE             1124
#define IDC_ATY_E_ANALYT_NAME           1125
#define IDC_PS_ACC_TYPE                 1125
#define IDC_ATY_B_ADD                   1126
#define IDC_ATY_B_DELETE                1127
#define IDC_ATY_B_EDIT                  1128
#define IDC_ATY_B_CHOOSE                1128
#define IDC_PS_ACC_ANALYT1              1129
#define IDC_ATY_B_NEXT                  1129
#define IDC_ATY_B_EXIT                  1130
#define IDC_ATY_LIST                    1131
#define IDC_PS_ACC_ANALYT2              1131
#define IDC_ATY_B_PREV                  1132
#define IDC_ACO_LIST                    1135
#define IDC_PS_EMPLNAME                 1136
#define IDC_PS_WNDID                    1137
#define IDC_PS_WNDNAME                  1138
#define IDC_PS_LIST                     1139
#define IDC_PS_ANALYT_TYPE              1140
#define IDC_PS_S_ACC_CODE               1140
#define IDC_PS_ACC_CODE                 1141
#define IDC_PS_E_ACC_CODE               1141
#define IDC_PS_ACC_NAME                 1142
#define IDC_PS_E_ACC_NAME               1142
#define IDC_PS_C_ACC_TYPE               1143
#define IDC_PS_B_EXIT                   1144
#define IDC_PS_B_ADD                    1145
#define IDC_PS_C_ANALYT1                1146
#define IDC_PS_C_ANALYT2                1147
#define IDC_PS_B_DELETE                 1148
#define IDC_PS_S_ACC_NAME               1149
#define IDC_PS_B_CHOOSE                 1150
#define IDC_PS_B_PREV                   1151
#define IDC_PS_B_NEXT                   1152
#define IDC_ATY_G_1                     1153
#define IDC_ATY_G_2                     1154
#define IDC_ATY_G_3                     1155
#define IDC_ACO_G_2                     1156
#define IDC_ACO_G_1                     1157
#define IDC_ACO_C_ANALYT_TYPE           1158
#define IDC_PS_G_1                      1159
#define IDC_PS_G_2                      1160
#define IDC_PS_G_3                      1161
#define IDC_OPD_EMPLNAME                1162
#define IDC_OPD_WNDID                   1163
#define IDC_OPD_WNDNAME                 1164
#define IDC_OPD_S_DOC_CODE              1165
#define IDC_OPD_E_DOC_CODE              1166
#define IDC_OPD_S_DOC_NAME              1167
#define IDC_OPD_E_DOC_NAME              1168
#define IDC_OPD_C_ANALYT3               1169
#define IDC_DRE_E_DEBET_NAME            1169
#define IDC_OPD_ACC_ANALYT1             1170
#define IDC_DRE_E_CREDIT_CODE           1170
#define IDC_OPD_C_ANALYT1               1171
#define IDC_DRE_E_CREDIT_NAME           1171
#define IDC_OPD_ACC_ANALYT2             1172
#define IDC_OPD_ACC_ANALYT3             1173
#define IDC_OPD_C_ANALYT2               1174
#define IDC_OPD_B_CHOOSE                1175
#define IDC_OPD_B_PREV                  1176
#define IDC_OPD_B_NEXT                  1177
#define IDC_OPD_B_ADD                   1178
#define IDC_OPD_B_DELETE                1179
#define IDC_OPD_B_EXIT                  1180
#define IDC_DRE_B_REGISTER              1181
#define IDC_OPD_C_TYPE_1                1182
#define IDC_OPD_C_TYPE_2                1183
#define IDC_OPD_C_TYPE_3                1184
#define IDC_OPD_G_1                     1185
#define IDC_OPD_G_2                     1186
#define IDC_OPD_G_3                     1187
#define IDC_OPD_LIST                    1188
#define IDC_THO_EMPLNAME                1189
#define IDC_THO_WNDID                   1190
#define IDC_THO_G_1                     1191
#define IDC_THO_G_2                     1192
#define IDC_THO_G_3                     1193
#define IDC_THO_S_OPERATION             1194
#define IDC_THO_E_OPERATION             1195
#define IDC_THO_C_DOC_CODE              1197
#define IDC_THO_S_DOC_CODE              1198
#define IDC_THO_S_DEBET                 1199
#define IDC_THO_S_CREDIT                1200
#define IDC_THO_B_EXIT                  1201
#define IDC_THO_B_DELETE                1202
#define IDC_THO_B_ADD                   1203
#define IDC_THO_B_NEXT                  1204
#define IDC_THO_B_PREV                  1205
#define IDC_THO_B_CHOOSE                1206
#define IDC_THO_C_CREDIT                1207
#define IDC_THO_C_DEBET                 1208
#define IDC_THO_LIST                    1209
#define IDC_THO_WNDNAME                 1210
#define IDC_DRE_WNDNAME                 1211
#define IDC_DRE_WNDID                   1212
#define IDC_DRE_EMPLNAME                1213
#define IDC_DRE_LIST                    1214
#define IDC_DRE_G_1                     1215
#define IDC_DRE_G_2                     1216
#define IDC_DRE_D_DATEFROM              1217
#define IDC_DRE_S_DATE_FROM             1218
#define IDC_DRE_G_3                     1219
#define IDC_DRE_S_SLASH                 1220
#define IDC_DRE_S_ANALYT1               1221
#define IDC_DRE_S_ANALYT2               1222
#define IDC_DRE_S_ANALYT3               1223
#define IDC_DRE_E_A1_VA                 1224
#define IDC_DRE_E_A2_VA                 1225
#define IDC_DRE_E_A3_VA                 1226
#define IDC_DRE_E_A1_T                  1227
#define IDC_DRE_E_A2_T                  1228
#define IDC_DRE_E_A3_T                  1229
#define IDC_DRE_S_SUM                   1233
#define IDC_DRE_E_SUM                   1234
#define IDC_DRE_C_DOC                   1235
#define IDC_DRE_S_DOC                   1236
#define IDC_DRE_S_SEPARATOR             1237
#define IDC_DRE_S_OPERATION             1238
#define IDC_DRE_C_OPERATION             1239
#define IDC_DRE_E_DEBET_CODE            1240
#define IDC_DRE_B_CHOOSE                1241
#define IDC_DRE_B_PREV                  1242
#define IDC_DRE_B_NEXT                  1243
#define IDC_DRE_B_ADD                   1244
#define IDC_DRE_B_DELETE                1245
#define IDC_DRE_B_EXIT                  1246
#define IDC_DRE_C_A1_KAU                1247
#define IDC_LRJ_LIST                    1247
#define IDC_DRE_C_A2_KAU                1248
#define IDC_LAB_LIST                    1248
#define IDC_DRE_C_A3_KAU                1249
#define IDC_KRV_EDIT                    1249
#define IDC_KRV_B_EXIT                  1250
#define IDC_KRJ_B_EXIT                  1251
#define IDC_KRJ_EDIT                    1252

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1253
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
