//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется oeav.rc
//
#define IDD_REGIST_LIST                 9
#define IDD_OEAV_DIALOG                 102
#define IDD_BALANCE_REP                 103
#define IDD_CARDFILES                   104
#define IDD_DOCUMENTS                   105
#define IDD_LOOK_RL                     106
#define IDD_LOOK_AB                     107
#define IDD_DEF_REP_FORM                108
#define IDD_ANALYTICAL_CODES            109
#define IDR_MAINFRAME                   128
#define IDI_CREATE                      129
#define IDI_PRINT                       131
#define IDI_FOLDER                      132
#define IDI_FREPORT                     133
#define IDI_BCREPORT                    134
#define IDI_INVENTORY                   135
#define IDI_ANALITIC                    136
#define IDI_OPERATION                   137
#define IDI_DOCUMENT2                   138
#define IDI_PLAN                        139
#define IDI_CODES                       140
#define IDI_ICON1                       141
#define IDI_INPUT                       141
#define IDI_NEXT                        142
#define IDI_PREVIOUS                    143
#define IDI_CANCEL                      144
#define IDI_DELETE                      145
#define IDI_CANCEL2                     146
#define IDI_ADD                         147
#define IDI_ACCEPT                      149
#define IDC_STATIC_MAIN_MENU            1000
#define IDC_STATIC_ID                   1001
#define IDC_STATIC_NAME                 1002
#define IDC_RS_TITLE                    1002
#define IDC_TAB_CONTROLLER              1005
#define IDC_BUTTON_SETTINGS             1006
#define IDC_BUTTON_EXIT                 1007
#define IDR_SETTINGS                    1008
#define IDR_EXIT                        1009
#define IDC_RS_EMPLID                   1010
#define IDC_RL_B_LOOKRL                 1011
#define IDC_RL_B_LOOKAB                 1012
#define IDC_RL_B_LOOKRL_Q               1013
#define IDC_BUTTON4                     1014
#define IDC_RL_B_LOOKAB_Q               1014
#define IDC_RL_B_GENERATEAB             1015
#define IDC_RL_B_PRINT_AB               1016
#define IDR_LOOK_BOOK                   1018
#define IDR_LOOK_BOOK2                  1019
#define IDC_LOOKG                       1020
#define IDC_GROUP_Q                     1021
#define IDC_BR_TITLE                    1022
#define IDC_BR_EMPLID                   1023
#define IDC_DC_TITLE                    1026
#define IDC_DC_EMPLID                   1027
#define IDC_CF_TITLE                    1028
#define IDC_CF_EMPLID                   1029
#define IDC_BR_B_REP_DEF                1030
#define IDC_BR_B_OSV_PERIOD             1031
#define IDC_BR_B_LIST_O_PERIOD          1032
#define IDC_CF_B_OPD                    1032
#define IDC_BR_B_BAL_REP_PERIOD         1033
#define IDC_CF_B_PS                     1033
#define IDC_DC_B_MINV                   1033
#define IDC_CF_B_THO                    1034
#define IDC_LRJ_EMPLID                  1034
#define IDC_CF_B_VA                     1035
#define IDC_LRJ_WNDID                   1035
#define IDC_CF_B_KAY                    1036
#define IDC_LRJ_WNDNAME                 1036
#define IDC_LRJ_DATE                    1037
#define IDC_LRJ_DOCUMENT                1038
#define IDC_LRJ_OPERATION               1039
#define IDC_LRJ_E_DATE_FROM             1040
#define IDC_LRJ_E_DOC_NAME              1041
#define IDC_LRJ_E_DOC_ID                1042
#define IDC_LRJ_E_OPERATION             1043
#define IDC_LRJ_DATE_FROM               1044
#define IDC_LRJ_E_DATE                  1045
#define IDC_LRJ_DEBET                   1046
#define IDC_LRJ_E_DEBET_CASH            1047
#define IDC_LRJ_E_DEBET_SOURCE          1048
#define IDC_LRJ_CREDIT                  1049
#define IDC_LRJ_E_CREDIT_CASH           1050
#define IDC_LRJ_E_CREDIT_SOURCE         1051
#define IDC_LRJ_SUM                     1052
#define IDC_LRJ_E_SUM                   1053
#define IDC_LRJ_E_CREDIT_SOURCE2        1054
#define IDC_LRJ_DELETE                  1055
#define IDC_LRJ_NEXT                    1056
#define IDC_LRJ_EXIT                    1057
#define IDC_LRJ_PREV                    1058
#define IDC_LAB_EMPLID                  1060
#define IDC_LAB_WNDID                   1061
#define IDC_LAB_DATE                    1062
#define IDC_LAB_WNDNAME                 1063
#define IDC_LAB_DOCUMENT                1064
#define IDC_LAB_OPERATION               1065
#define IDC_LAB_E_DATE                  1066
#define IDC_LAB_E_DOC_NAME              1067
#define IDC_LAB_E_DOC_ID                1068
#define IDC_LAB_E_OPERATION             1069
#define IDC_LAB_DATE_FROM               1070
#define IDC_LAB_E_DATE_FROM             1071
#define IDC_LAB_DEBET                   1072
#define IDC_LAB_E_DEBET_CASH            1073
#define IDC_LAB_CREDIT                  1074
#define IDC_LAB_E_CREDIT_CASH           1075
#define IDC_LAB_E_ACC_ID                1076
#define IDC_ACCOUNT                     1077
#define IDC_LAB_E_ACC_NAME              1078
#define IDC_LAB_SEP_1                   1079
#define IDC_LAB_E_CORR_ID               1080
#define IDC_LRJ_SEP_2                   1080
#define IDC_LAB_E_CORR_NAME             1081
#define IDC_LRJ_SEP_3                   1081
#define IDC_LAB_SEP_2                   1082
#define IDC_LAB_SEP_3                   1085
#define IDC_CORR                        1086
#define IDC_LAB_DELETE                  1087
#define IDC_LAB_PREV                    1088
#define IDC_LAB_NEXT                    1089
#define IDC_LAB_EXIT                    1090
#define IDC_LRJ_SEP_1                   1091
#define IDC_DRF_B_EXIT                  1092
#define IDC_DRF_EMPLNAME                1093
#define IDC_DRF_WNDID                   1094
#define IDC_DRF_WNDNAME                 1095
#define IDC_DRF_D_INTERVAL_FROM         1096
#define IDC_DRF_INT_FROM                1097
#define IDC_DRF_D_INTERVAL_TO           1098
#define IDC_DRF_INT_TO                  1099
#define IDC_DRF_ACCOUNT                 1100
#define IDC_DRF_C_ACC                   1104
#define IDC_ACO_EMPLNAME                1107
#define IDC_ACO_WNDID                   1108
#define IDC_ACO_WNDNAME                 1109
#define IDC_ACO_ANALYT_TYPE             1110
#define IDC_ACO_E_ANALYT_CODE           1111
#define IDC_ACO_E_ANALYT_CODE2          1112
#define IDC_ACO_E_ANALYT_TYPE           1112
#define IDC_ACO_C_ANALYT_TYPES          1113
#define IDC_ACO_B_EXIT                  1114
#define IDC_ACO_B_ADD                   1115
#define IDC_ACO_B_PREV                  1116
#define IDC_ACO_B_NEXT                  1117
#define IDC_ACO_B_DELETE                1118
#define IDC_ACO_ANALYT_CODE             1119

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1120
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
